name: 'Sync Repo to CODING'
description: 'Sync Repository to CODING'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  github-repo:
    description: 'GitHub 代码仓库的 SSH URL'
    required: true
    default: ''
  coding-repo:
    description: 'CODING 代码仓库的 SSH URL'
    required: true
    default: ''
  appname:
    description: '程序名称'
    required: true
    default: ''
  wgetsh:
    description: '下载sh'
    required: False
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-repo }}
    - ${{ inputs.coding-repo }}
    - ${{ inputs.appname }}
    - ${{ inputs.wgetsh }}
